kind: pipeline
name: default
steps:
  - name: build-gatsby-preview-docker
    image: plugins/docker
    settings:
      repo: registry.pixelpoint.io/flagsmith-preview
      registry: registry.pixelpoint.io
      dockerfile: Dockerfile.preview
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - main
      event:
        exclude:
          - custom

  - name: deploy-gatsby-preview-server
    image: peloton/drone-k8s-deployment
    settings:
      insecure: false
      deployment_names: flagsmith-preview
      container_names: flagsmith-preview
      namespaces: websites
      docker_image: registry.pixelpoint.io/flagsmith-preview:latest
      date_label: deployment.drone.io/date-deployed
      url:
        from_secret: kubernetes_url
      token:
        from_secret: kubernetes_token
    when:
      branch:
        - main
      event:
        exclude:
          - custom

trigger:
  event:
    - push
    - custom
