name: Deploy Wordpress Preview Site

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo
              uses: actions/checkout@v3

            - name: Push to dokku
              uses: dokku/github-action@master
              with:
                  git_remote_url: "ssh://dokku@website-preview.flagsmith.io:22/website-preview"
                  ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
                  git_push_flags: "--force"
